-- ============================================================
-- AI Knowledge Maintenance — CockroachDB Schema
-- Persistent memory layer for agentic knowledge maintenance
--
-- Uses CockroachDB Distributed Vector Indexing for semantic search
-- on knowledge artifacts. All ID columns are TEXT (UUID strings
-- generated in Python) to avoid type casting issues across
-- the application boundary.
-- ============================================================

-- --------------------------------------------------------
-- agent_state: Persistent agent workflow state (Burr state machine)
-- CockroachDB serves as the agent's memory — workflow state survives
-- across Lambda invocations and agent restarts.
-- --------------------------------------------------------
CREATE TABLE IF NOT EXISTS agent_state (
    app_id          TEXT PRIMARY KEY,
    state_data      JSONB NOT NULL DEFAULT '{}'::jsonb,
    current_stage   TEXT NOT NULL DEFAULT 'initialized',
    assessment_id   TEXT,
    remediation_id  TEXT,
    status          TEXT NOT NULL DEFAULT 'active',
    created_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at      TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_agent_state_status
    ON agent_state (status);
CREATE INDEX IF NOT EXISTS idx_agent_state_stage
    ON agent_state (current_stage);
CREATE INDEX IF NOT EXISTS idx_agent_state_updated
    ON agent_state (updated_at DESC);

-- --------------------------------------------------------
-- knowledge_artifacts: Knowledge artifacts with vector embeddings
-- Uses CockroachDB VECTOR(384) for semantic similarity search
-- Embeddings generated by EmbeddingProvider (HuggingFace API or TF-IDF)
-- --------------------------------------------------------
CREATE TABLE IF NOT EXISTS knowledge_artifacts (
    artifact_id     TEXT PRIMARY KEY,
    artifact_uri    TEXT NOT NULL UNIQUE,
    artifact_type   TEXT NOT NULL DEFAULT 'document',
    source          TEXT NOT NULL DEFAULT 'local',
    content         TEXT NOT NULL DEFAULT '',
    metadata        JSONB NOT NULL DEFAULT '{}'::jsonb,
    embedding       VECTOR(384),
    created_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at      TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- Index for fast lookups by type and source
CREATE INDEX IF NOT EXISTS idx_artifacts_type
    ON knowledge_artifacts (artifact_type);
CREATE INDEX IF NOT EXISTS idx_artifacts_source
    ON knowledge_artifacts (source);

-- Vector index for semantic similarity search.
-- The <=> operator is cosine distance; the index op-class must match
-- so the optimizer uses the index instead of full-scanning.  CockroachDB
-- v25.2+ supports vector indexes (GA).  The vector_cosine_ops op-class
-- binds the index to the cosine distance metric used by <=>.
-- If IF NOT EXISTS is not supported for vector indexes on your cluster
-- version, this DDL is also executed defensively inside initialize_schema().
CREATE VECTOR INDEX IF NOT EXISTS idx_artifacts_embedding
    ON knowledge_artifacts (embedding vector_cosine_ops);

-- --------------------------------------------------------
-- knowledge_signals: Individual knowledge signals (findings)
-- Each signal is a bare fact about a knowledge artifact
-- --------------------------------------------------------
CREATE TABLE IF NOT EXISTS knowledge_signals (
    signal_id       TEXT PRIMARY KEY,
    artifact_uri    TEXT NOT NULL,
    collector_id    TEXT NOT NULL,
    signal_type     TEXT NOT NULL,
    severity        TEXT NOT NULL DEFAULT 'LOW',
    score           FLOAT NOT NULL DEFAULT 0.0,
    recommendation  TEXT NOT NULL DEFAULT '',
    ai_impact       TEXT NOT NULL DEFAULT '',
    evidence        JSONB NOT NULL DEFAULT '{}'::jsonb,
    status          TEXT NOT NULL DEFAULT 'new',
    last_seen       TIMESTAMPTZ NOT NULL DEFAULT now(),
    access_count    INT NOT NULL DEFAULT 0,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_signals_artifact
    ON knowledge_signals (artifact_uri);
CREATE INDEX IF NOT EXISTS idx_signals_collector
    ON knowledge_signals (collector_id);
CREATE INDEX IF NOT EXISTS idx_signals_status
    ON knowledge_signals (status);
CREATE INDEX IF NOT EXISTS idx_signals_severity
    ON knowledge_signals (severity);

-- --------------------------------------------------------
-- signal_lifecycle: Lifecycle tracking for signals
-- Tracks when signals first appeared, were resolved, recurred
-- Uses TEXT IDs to match knowledge_signals and knowledge_assessments
-- --------------------------------------------------------
CREATE TABLE IF NOT EXISTS signal_lifecycle (
    signal_id               TEXT PRIMARY KEY,
    first_seen              TIMESTAMPTZ NOT NULL DEFAULT now(),
    last_seen               TIMESTAMPTZ NOT NULL DEFAULT now(),
    first_assessment_id     TEXT,
    last_assessment_id      TEXT,
    resolved_assessment_id  TEXT,
    status                  TEXT NOT NULL DEFAULT 'new',
    assessment_ids          TEXT[] NOT NULL DEFAULT '{}',
    access_count            INT NOT NULL DEFAULT 0
);

CREATE INDEX IF NOT EXISTS idx_lifecycle_status
    ON signal_lifecycle (status);

-- --------------------------------------------------------
-- knowledge_assessments: Assessment snapshots over time
-- Each scan produces one assessment with dimension scores
-- --------------------------------------------------------
CREATE TABLE IF NOT EXISTS knowledge_assessments (
    assessment_id   TEXT PRIMARY KEY,
    score           FLOAT NOT NULL DEFAULT 0.0,
    dimensions      JSONB NOT NULL DEFAULT '{}'::jsonb,
    signals_count   INT NOT NULL DEFAULT 0,
    metadata        JSONB NOT NULL DEFAULT '{}'::jsonb,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_assessments_created
    ON knowledge_assessments (created_at DESC);

-- --------------------------------------------------------
-- assessment_signals: Junction table linking assessments to signals
-- Many-to-many: each assessment includes many signals,
-- each signal can appear in multiple assessments over time
-- --------------------------------------------------------
CREATE TABLE IF NOT EXISTS assessment_signals (
    assessment_id   TEXT NOT NULL,
    signal_id       TEXT NOT NULL,
    PRIMARY KEY (assessment_id, signal_id)
);

CREATE INDEX IF NOT EXISTS idx_as_assessment
    ON assessment_signals (assessment_id);
CREATE INDEX IF NOT EXISTS idx_as_signal
    ON assessment_signals (signal_id);

-- --------------------------------------------------------
-- problem_queue: Discovered knowledge problems ranked by salience
-- Problems are clusters of related signals that need remediation
-- --------------------------------------------------------
CREATE TABLE IF NOT EXISTS problem_queue (
    problem_id       TEXT PRIMARY KEY,
    category         TEXT NOT NULL,
    artifact_uris    JSONB NOT NULL DEFAULT '[]'::jsonb,
    salience         FLOAT NOT NULL DEFAULT 0.0,
    encoding_score   FLOAT NOT NULL DEFAULT 0.0,
    outcome_score    FLOAT NOT NULL DEFAULT 0.0,
    retrieval_score  FLOAT NOT NULL DEFAULT 0.0,
    staleness_factor FLOAT NOT NULL DEFAULT 1.0,
    status           TEXT NOT NULL DEFAULT 'open',
    description      TEXT NOT NULL DEFAULT '',
    created_at       TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at       TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_problems_status
    ON problem_queue (status);
CREATE INDEX IF NOT EXISTS idx_problems_salience
    ON problem_queue (salience DESC);
CREATE INDEX IF NOT EXISTS idx_problems_category
    ON problem_queue (category);

-- --------------------------------------------------------
-- wont_fix_signatures: Suppress re-discovery of wont-fix problems
-- --------------------------------------------------------
CREATE TABLE IF NOT EXISTS wont_fix_signatures (
    signature_id    TEXT PRIMARY KEY,
    category        TEXT NOT NULL,
    artifact_uris   JSONB NOT NULL DEFAULT '[]'::jsonb,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_wontfix_category
    ON wont_fix_signatures (category);

-- --------------------------------------------------------
-- remediation_history: Institutional memory of remediation outcomes
-- Used for EMA strategy scoring and historical context retrieval
-- The agent reads from this table before generating new proposals
-- --------------------------------------------------------
CREATE TABLE IF NOT EXISTS remediation_history (
    outcome_id           TEXT PRIMARY KEY,
    issue_type           TEXT NOT NULL,
    strategy             TEXT NOT NULL,
    strategy_description TEXT NOT NULL DEFAULT '',
    verification_outcome TEXT NOT NULL DEFAULT 'unchanged',
    score_before         FLOAT NOT NULL DEFAULT 0.0,
    score_after          FLOAT NOT NULL DEFAULT 0.0,
    proposal_reasoning   TEXT NOT NULL DEFAULT '',
    tokens_used          INT NOT NULL DEFAULT 0,
    latency_ms           FLOAT NOT NULL DEFAULT 0.0,
    forked               BOOL NOT NULL DEFAULT false,
    modification_steps    JSONB NOT NULL DEFAULT '[]'::jsonb,
    created_at           TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_history_issue_type
    ON remediation_history (issue_type);
CREATE INDEX IF NOT EXISTS idx_history_strategy
    ON remediation_history (strategy);
CREATE INDEX IF NOT EXISTS idx_history_outcome
    ON remediation_history (verification_outcome);
CREATE INDEX IF NOT EXISTS idx_history_created
    ON remediation_history (created_at DESC);

-- --------------------------------------------------------
-- decision_traces: Full reasoning chain for each remediation step
-- Observability for the agentic workflow
-- --------------------------------------------------------
CREATE TABLE IF NOT EXISTS decision_traces (
    trace_id        TEXT PRIMARY KEY,
    outcome_id      TEXT,
    stage           TEXT NOT NULL,
    reasoning       TEXT NOT NULL DEFAULT '',
    llm_metadata    JSONB NOT NULL DEFAULT '{}'::jsonb,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_traces_outcome
    ON decision_traces (outcome_id);

-- --------------------------------------------------------
-- skip_events: Records of when processing was skipped
-- Signal-delta gates, autonomy gates, etc.
-- --------------------------------------------------------
CREATE TABLE IF NOT EXISTS skip_events (
    skip_id         TEXT PRIMARY KEY,
    lane            TEXT NOT NULL,
    reason          TEXT NOT NULL,
    config_key      TEXT NOT NULL DEFAULT '',
    artifact_uri    TEXT NOT NULL DEFAULT '',
    created_at      TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_skips_lane
    ON skip_events (lane);
CREATE INDEX IF NOT EXISTS idx_skips_created
    ON skip_events (created_at DESC);

-- --------------------------------------------------------
-- modified_artifacts: Track which artifacts were modified by
-- executor runs. Enables later runs to include these files in
-- the artifact set even when limiting to N artifacts.
-- Stores only URIs (not content) — lightweight tracking.
-- Persists in CockroachDB so later runs (even on different
-- cloud machines) can query which files were previously fixed.
-- --------------------------------------------------------
CREATE TABLE IF NOT EXISTS modified_artifacts (
    artifact_uri    TEXT NOT NULL,
    source          TEXT NOT NULL DEFAULT '',
    run_idx         INT NOT NULL DEFAULT 0,
    step_type       TEXT NOT NULL DEFAULT '',
    modified_at     TIMESTAMPTZ NOT NULL DEFAULT now(),
    PRIMARY KEY (artifact_uri, source)
);

CREATE INDEX IF NOT EXISTS idx_modified_source
    ON modified_artifacts (source);
